### PR TITLE
Fix ToolCard clickable layout

### PR DESCRIPTION
**Pull request by Ghadyk**
This PR addresses an issue with the ToolCard click action not being too clear.

- The ToolCard is now clickable as an element with cursor and hover effect.
- Votes in ToolCard now has a fixed width to avoid layout shift on load
- TagList fixed click routing and more/less button layout

**Current Card Layout:**

_Desktop ToolCard_
Screenshot 2024-04-13 181433

_Mobile ToolCard_
Screenshot 2024-04-13 181447

**New Card Layout:**

_Desktop ToolCard_
Screenshot 2024-04-13 181500

_Mobile ToolCard_
Screenshot 2024-04-13 181511

### CODE REVIEW

**Comment by mre** [comment]
Looks good.


First I thought it was broken because it didn't load when I clicked on the card.
Turns out I had to click into the free space and not the text.
Not sure if that's on purpose. Might make sense that the text is still selectable,
but it could also be confusing to other people.

I somehow got used to the "clickout" button on the right.
Do you think that button is too heavy for the UI?

The clickout button conveys the information that there is more info.
Without that, I have few visual cues that that's the case.
Especially on mobile where there is no mouse hover.

**Comment by mre** [comment]
I like the design on mobile and the blue frame around the tool cards on desktop.
From a UI perspective we can keep it this way.
Link somehow doesn't work if I click on the card. (I'm on Firefox.) That's something we should change.

**Comment by mre** [comment]
👍 fix or 👎 close?

**Comment by Ghadyk** [comment]
I will fix the click area issue.
What are your thought on the new design?

Since we have a lot of data to show, to me it makes more sense to leave as much as we can, the clickout button was pushing everything.
I could also find a new place for it, maybe something similar to the mobile design?

**Comment by mre** [comment]
I like it; especially the mobile view.

Also tried `flex-direction: column;` for the mobile view of the `languageCardWrapper`, and it also looks nice to me:

image

When the vote is at the top, it's more prominent to me. What are your thoughts?

**Comment by mre** [comment]
Decided to merge it as it's definitely an improvement. We can continue work on `main`.

**Pull request merged**
